In [22]:
#Move the data file in input folder. List the files present in the input folder.
import os
print(os.listdir("input"))

['data.json']

In [23]:
#Libraries
import json 
import pandas as pd 

#load input json file into an json list of json objects
json_array = []
for line in open('input/data.json', 'r'):
    json_array.append(json.loads(line))

In [24]:
# iterate through json array and take the values of uuid and payload into 2 separate lists
uuid=[]
payload= []
for my_json_dict in json_array:
    uuid.append(my_json_dict['uuid'])
    payload.append(my_json_dict['payload'])
    
#merge payload and uuid into a single dataframe
location_df =pd.DataFrame(payload)
location_df['uuid']=uuid
#List the columns in the dataframe
location_df.columns

Index(['_geocode_quality', '_records_touched', 'address', 'address_extended',
       'admin_region', 'category_ids', 'category_ids_text_search',
       'category_labels', 'country', 'domain_aggregate', 'email', 'existence',
       'existence_full', 'existence_ml', 'fax', 'geo_virtual',
       'geocode_confidence', 'geocode_level', 'hours', 'hours_display',
       'languages', 'latitude', 'locality', 'longitude', 'name',
       'name_variants', 'neighborhood', 'placerank', 'placerank_ml', 'po_box',
       'post_town', 'postcode', 'region', 'review_count', 'search_tags',
       'status', 'status_closed', 'tel', 'website', 'yext_id', 'uuid'],
      dtype='object')

In [25]:
#Peek inside the data. location_df will be used as a base dataframe to solve all the questions
location_df.head()

,_geocode_quality,_records_touched,address,address_extended,admin_region,category_ids,category_ids_text_search,category_labels,country,domain_aggregate,...,postcode,region,review_count,search_tags,status,status_closed,tel,website,yext_id,uuid
0,4,"{""crawl"":8,""lssi"":0,""polygon_centroid"":0,""geoc...","The Lodge, Dunottar",NaN,Scotland,[108],,"[[Landmarks, Buildings and Structures]]",gb,,...,AB39 2TL,Kincardineshire,719,"[Dunnottar Castle Aberdeenshire, Dunotter Castle]",1,NaN,01569 762173,http://www.dunnottarcastle.co.uk,NaN,3867aaf3-12ab-434f-b12b-5d627b3359c3
1,4,"{""crawl"":11,""lssi"":0,""polygon_centroid"":0,""geo...",Cherry Park,NaN,Scotland,[347],,"[[Social, Food and Dining, Restaurants]]",gb,,...,PA32 8XE,Argyll,532,"[Inveraray Castle Tea Room, Inverary Castle]",1,NaN,01499 302203,http://www.inveraray-castle.com,NaN,8278ab80-2cd1-4dbd-9685-0d0036b681eb
2,2,"{""crawl"":7,""lssi"":0,""polygon_centroid"":0,""geoc...",,NaN,England,[108],,"[[Landmarks, Buildings and Structures]]",gb,,...,SL4 1NJ,Berkshire,,"[The Windsor Castle, The Windsor Castle Pub, T...",1,NaN,020 7766 7304,http://www.royalcollection.org.uk/visit/windso...,NaN,c5f7d8a9-0851-46ef-8da7-ad55e187d3a8
3,4,"{""crawl"":6,""lssi"":0,""polygon_centroid"":0,""geoc...",,NaN,Scotland,[109],,"[[Landmarks, Gardens]]",gb,,...,AB41 7PD,Aberdeenshire,2,NaN,1,NaN,01651 842352,http://www.nts.org.uk/Property/Pitmedden-Garden,NaN,bb57a153-740f-42be-aa4d-ae12d4eb57d4
4,4,"{""crawl"":13,""lssi"":0,""polygon_centroid"":0,""geo...",Off A55 Highway,NaN,Wales,[110],,"[[Landmarks, Historic and Protected Sites]]",gb,,...,LL57 4HN,Gwynedd,13,"[Penrhyn Castle Gwynedd, Penrhyn Castle Railwa...",1,NaN,01248 353084,http://www.nationaltrust.org.uk/penrhyn-castle,NaN,c38a4813-8f52-4eea-bef2-65a8ebba2c1c

In [26]:
#To find the rows and columns of the dataframe
location_df.shape

(538, 41)

In [27]:
# 1. Return every unique locality (cf. city) along with how often it occurs

#Get the count for each unique locality using pandas function value_counts
location_df['locality'].value_counts()
#answer is the output of the above statement

London                 149
Edinburgh               23
Liverpool               15
Glasgow                 15
Oxford                  13
Cardiff                 12
Cambridge               12
York                    10
Manchester              10
Aberdeen                 9
Bath                     8
Brighton                 8
Canterbury               6
Stirling                 6
Birmingham               6
Newcastle upon Tyne      6
Leeds                    5
Bristol                  5
Salisbury                4
Durham                   4
Lincoln                  4
Norwich                  4
Sheffield                4
Chichester               4
Nottingham               3
Dunster                  3
Derby                    3
Kirkwall                 3
Stratford-upon-Avon      3
Winchester               3
                      ...
Dartmouth                1
Middlesbrough            1
Christchurch             1
Fleetwood                1
Burnley                  1
Newton Abbot             1
Edwinstowe               1
Arundel                  1
Rye                      1
Faversham                1
Hale Village             1
Chagford                 1
Uxbridge                 1
Bradford-on-Avon         1
Tarves                   1
Bridgend                 1
Tattershall              1
Castle Fraser            1
Southampton              1
Reading                  1
Portsmouth               1
Wolverhampton            1
Trevor                   1
Carlisle                 1
Belfast                  1
Aylesford                1
Blackburn                1
Whitehaven               1
Broomfield               1
West Bromwich            1
Name: locality, Length: 178, dtype: int64

In [28]:
# 2. Return all addresses that start with a number (return just the address)

#Initialize a list to hold numeric addresses
numeric_adresses=[]
#iterate through the list and drop null values
for temp in list(location_df['address'].dropna().values):
    #split the data to create a list of addresses and check if first letter of address is numeric
    if temp.split() and temp.split()[0][0].isnumeric():
        #add the unpadded address to final list of numeric adress
        numeric_adresses.append(temp.strip())
        
#Ans: numeric_address is the final list of all addresses that start with a number
numeric_adresses

["52 Pritchatt's Rd",
 '1 Bridge Rd',
 '1 Charlie Chaplin Walk',
 '1 Danes Ter',
 "1 King's Parade",
 '1 Kinnerton St',
 '1 Lime St',
 '1 Occam Ct',
 '1 Princes St',
 '1 Queen St',
 '1 Sir Matt Busby Way',
 '1 The Cloisters',
 '1 The Oasis',
 '1 Western Gateway',
 '1-2 High St',
 '1-5 Lambeth Rd',
 '1-7 Davies Mews',
 '10 Church St',
 '10 Dumbreck Rd',
 '10 Mathew St',
 '10 Pilgrim St',
 '100 Grey St',
 '100 London Rd',
 '100 Pointhouse Rd',
 '105-119 Brentfield Rd',
 '11 The Precincts',
 '12 College Green',
 '12 Crooms Hill',
 '12 Holland Park Rd',
 '12 Kingston Buildings',
 '12 The Close',
 '127 Ledbury Rd',
 "13 Lincoln's Inn Fields",
 '134 Corstorphine Rd',
 '136 Kingsland Rd',
 '149 Piccadilly',
 '15 Old Chatham Rd',
 '15 The Strait',
 '150 Edmiston Dr',
 '150 London Wall',
 '16 Royal Cr',
 '167 Renfrew St',
 '17 Court St',
 '17 Gough Sq',
 '17 Shorts Gardens',
 '17 Sloane St',
 '174 Woodlands Rd',
 '18 Folgate St',
 '18 Stafford Ter',
 '18-19 Iron Gate',
 '188-196 Regent St',
 '197 Piccadilly',
 "2 King's Bench Walk",
 '20 Deans Yard',
 '2060 Pollokshaws Rd',
 '2060 Pollokshaws Rd',
 '207 High St',
 '20A Inverleith Row',
 '21 New Globe Walk',
 '22 Edward Pavilion',
 '221b Baker St',
 '25 High St',
 '25 The Precincts',
 '26 Whitehall',
 '27 Castlegate',
 "27 St James's Pl",
 '272 Canongate',
 '3 Quay St',
 '3 Saint Helens St',
 '30 Orange St',
 '35 Cranbourn St',
 '354 Queenstown Rd',
 '36 St Andrew Sq',
 '36 Wigmore St',
 '39 Walbrook',
 '4 Richmond Mews',
 '4/5 Pavilion Buildings',
 '40 Hope St',
 '40 Southwark St',
 '42 Francis St',
 '43 Upper Brook St',
 '45 Queen Caroline St',
 '45-49 Berry St',
 '477B Lawnmarket',
 '48 Gardner St',
 '48 Hopton St',
 '5 Blythswood Sq',
 '5 Cultins Rd',
 '5-6 Leicester Sq',
 '5-7 Eastgate St',
 '50 Pacific Quay',
 '50 Porters Walk',
 "50 St Katharine's Way",
 '51 Piccadilly',
 '525 Ocean Boulevard',
 '55/61 Westbourne Ter',
 '6 The Cl',
 '602 Marlborough Gate',
 '7 - 9 Fore St',
 '7 David Wilson Pk',
 '7 Hurst St',
 '7-8 Park Pl',
 '70 Cathedral Sq',
 '71 Tanner St',
 '73 Belford Rd',
 '73 Brudenell Rd',
 '748 High Rd',
 '75 Belford Rd',
 '77 Borough High St',
 '77-82 Whitechapel High St',
 '78 Ballydrain Rd',
 '8 Benet St',
 '8 College Yard',
 '8 Hart St',
 '8 S Sq',
 '8 Southwark St',
 '8-10 Lampton Rd',
 '83 London Rd',
 '87 Dunluce Rd',
 '87-135 Brompton Rd',
 '9 Ellon Rd',
 '9 Lendal',
 '9 North Pallant',
 '9 The Cl',
 '92-94 High St',
 '96 Euston Rd',
 "97-99 King's Rd",
 '78 Princes St',
 '21 Hunts Bank']

In [30]:
# 3. Return all rows with addresses that don't contain a number (return the entire row)

#has_numbers check for each address, if it contains a number and returns a dictionary with string and boolean values
def hasNumbers(address_list):
    address_boolean_dict = {} 
    for inputString in address_list:
        inputString = str(inputString)
        if inputString!='':
            address_boolean_dict[inputString]=any(char.isdigit() for char in inputString)
    return address_boolean_dict
#create a list of addresses and drop null adresses
address_list=[]
for address in list(location_df['address'].dropna().values):
     address_list.append(address)
        
#call hasnumbers to find all the addresses which does not contain a number[Value is False]
address_boolean_dict = hasNumbers(address_list)

#return addresses which does not contain a number
alpha_address = []
for k in address_boolean_dict:
    if not address_boolean_dict[k]:
        alpha_address.append(k)

In [31]:
#check the addresses obtained
alpha_address

['The Lodge, Dunottar',
 'Cherry Park',
 'Murcot Rd',
 'Stratford City',
 'Nant Peris Road',
 'High St',
 'London, England',
 'Babington. Kilmersdon. Mendip',
 'Trinity St',
 'West Carriage Drive',
 'Clifton Down',
 'Exhibition Rd',
 'The Cl',
 'Royal Shakespeare Theatre',
 'Stag Hill',
 'The Sq',
 'st. Threadneedle',
 'Abbey Craig, Hillsfoots Rd',
 'Abchurch Lane',
 'Aberdeen & Grampian',
 'Airport Way',
 'Albert Dock',
 'Albert Dock, Liverpool Waterfront',
 'Alexandra Palace Way, Wood Green',
 'All Hallows by the Tower, Byward St',
 'Alnwick Castle',
 'Anfield Rd',
 'Ann St',
 'Arena Sq',
 'Arena Way',
 'Argyle St',
 'Art Gallery, Schoolhill',
 'Ashton New Rd',
 'Aston Triangle',
 'Aviation House',
 'Ballyrobin Rd',
 'Bankside',
 'Barnoon Hill',
 'Bartholomew Lane',
 'Battersea Pk',
 'Beaumont St',
 'Bedford Way',
 'Belvedere Rd',
 'Bennett St',
 'Bigbury-on-Sea',
 'Birmingham Rd',
 'Boar Lane City Sq',
 'Bolero Sq, The Lace Market',
 'Bovey Tracey',
 'Bow St',
 'Brayford Pool',
 'Brecon Rd',
 'Brewhouse Yard',
 'Britannia Rd',
 'Broad St',
 'Brooklands Dr',
 'Broughton Lane',
 'Brownlow Hill',
 'Buckingham Palace Rd',
 'Bucklers Hard',
 'Burlington Lane',
 'Bute Pl',
 'Canongate Tolbooth',
 'Carbis Bay',
 'Castle Ave',
 'Castle Ditch',
 'Castle Donington',
 'Castle Esplanade',
 'Castle Green',
 'Castle Hill',
 'Castle Lane',
 'Castle Lodge',
 'Castle Meadow',
 'Castle St',
 'Castle Way',
 'Cathays Pk',
 'Cathedral Green',
 'Chambers St',
 'Charterhouse Sq',
 'Cheapside',
 'Chester Rd',
 'Chesterfield Walk',
 'Church House',
 'Church St',
 'City Campus',
 'Claverton Down',
 'Claverton Manor',
 'Clive Steps, King Charles St',
 'Cloth Fair',
 'Coldra Woods, The Usk Valley',
 'College St',
 'Bodnant Rd',
 'Commercial St',
 'Coppergate',
 'Court Yard',
 'Covent Garden Piazza',
 'Cowcaddens Rd',
 'Craigmillar Castle Rd',
 'Crescent Rd',
 'Cromwell Rd',
 'Doddington Hall',
 'Dogdyke Rd',
 'Donington Pk',
 'Drake Circus',
 'Duke St',
 'Dulwich Common',
 'Durham Rd',
 'Duxford Airfield',
 'Farburn Terrace',
 'East Rd',
 'Elland Rd',
 'Elvet Hill Rd',
 'Enterprise House, Bassingbourn Rd',
 'Euston Rd',
 'Exmoor National Pk',
 'Eye of York',
 'Brands Hatch Rd',
 'First Av',
 'Fleet St',
 'Fore St',
 'Fossgate',
 'Foundry St',
 'Fulham Rd',
 'Gallery Rd',
 'Gidleigh Pk',
 'Glasgow Airport Limited',
 'Golf Rd',
 'Goodison Rd',
 'Grahame Park Way',
 'Graylingwell Dr',
 'Great Russell St',
 "Great St Helen's",
 'Great Western Dockyard',
 'Green St',
 'Guestrow',
 'Guild St',
 'Ham St',
 'Hampstead Grove',
 'Harbury Lane',
 'Harford Rd',
 'Haymarket',
 'Heathrow Airport, Bath Rd',
 'Henley St',
 'Hertford House',
 'Hidcote Bartrim',
 "Hilder's Cliff",
 'Hogarth Lane, Great West Rd',
 'Horning Rd',
 'Hornsey Rd',
 'Horse Guards Rd',
 'Horse Guards, Whitehall',
 'Houses of Parliament',
 'Howard St',
 'Hylas Lane',
 'Jersey Rd',
 'John Montagu Building',
 'Jubilee Rd',
 'Kensington Gardens, Albert Memorial Rd',
 'Kensington Gore',
 'Kensington High St',
 'King Edwards Rd',
 'King St',
 'King William St',
 'King William Walk',
 "King's Parade",
 'Kings Dock, Liverpool Waterfront',
 'Kings Hedges Rd',
 'Kingston Lane',
 'Kirby Misperton',
 'Lambeth Rd',
 'Lampeter Campus',
 'Leckwith Rd',
 'Leeman Rd',
 'Lime Rd',
 'Liverpool Rd',
 'Loch Lomond',
 'London Bridge',
 'London Rd',
 'The Estate Office',
 'Longport, Canterbury CT',
 'Longthorns',
 'Lower Mosley St',
 'Madeira Dr',
 'Main Rd',
 'Olympic House',
 'Mannington Hall',
 'Market Pl',
 'Marylebone Rd',
 'Methlick',
 'Metrocentre',
 'Middle Temple Lane',
 'Mile End Rd',
 'Mill Lane',
 'Millbank',
 'Minster Precincts',
 'Monument Street and Fish Street Hill',
 'Morvah Rd',
 'Mount Pleasant',
 'Muncaster Castle',
 'Museum Av',
 'Navigation House, Airport Way',
 'Newgate St',
 'Newlands Rd',
 'North Holmes Rd',
 'North Side Rd',
 'North York Moors National Pk',
 'Nr Amesbury',
 'Nuttall St',
 'Ocean Dr',
 'Old College, South Bridge',
 'Old Town',
 'Outer Circle, Regents Pk',
 'Overleigh Rd',
 'Palace Green',
 'Park Lane',
 'Park Row',
 'Parks Rd',
 'Parley Lane',
 'Parliament Sq',
 'Pen-y-Fai',
 'Pendigo Way',
 'Penfold Hill',
 'Peter St',
 'Phoenix Way',
 'Prebendal House',
 'Priory Dr',
 'Priory St',
 'Queensgate',
 'Regional Resource Centre',
 'Riverside Bldg, County Hall, Westminster Bridge Rd',
 'Roman Way',
 'Romney Rd',
 'Royal Exchange Sq',
 'Royal Hospital Rd',
 'Royal Mile',
 'Russell Pl',
 'Saint Nicholas Av',
 'Saltgrass Lane',
 'Sandwick',
 'Serpentine Rd',
 'Shambles, City Centre',
 'Shiprow',
 'Silk St, Barbican',
 'Silver St',
 'Silverstone Circuit',
 'Slade House Farm',
 'South Africa Rd',
 'South Parks Rd',
 'South Queensferry',
 'South Terminal',
 'Southam Road',
 'Southbank Centre, Belvedere Rd',
 'Southend Airport',
 'Sparkwell',
 'Speke Hall Av',
 'Spring Grove',
 'Squires Gate Lane',
 "St Andrew's St",
 "St Augustine's Parade",
 'St Cuthbert St',
 'St Giles',
 "St James' Mount",
 "St John's St",
 'St Margaret St',
 "St Margaret's Church Lothbury",
 "St Martin's Pl",
 'St Mary at Hill Eastcheap',
 "St Paul's Churchyard",
 "St Thomas's Sq",
 'St. Aldates',
 'St. Andrews Bay',
 'St. Fagans',
 'St. John St',
 'St Mellion',
 "St. Michael's Rd",
 'Stable Yard',
 'Staines Rd',
 'Stall St',
 'Stanley Matthews Way',
 'Station Rd',
 'Stocker Rd',
 'Stockton Rd',
 'Stour St',
 'The Strand',
 'Strawberry Pl',
 'Stuart St',
 'Sunken Gardens, Western Esplanade',
 'Sussex House',
 "Swain's Lane",
 'Swinecote Rd',
 'Sleaford Rd',
 'Tees Valley',
 'The Castle',
 'The Chanonry',
 'The College',
 'The Compass Centre, Nelson Rd',
 'The Cross',
 'The Esplanade',
 'The Estate Office Castle Howard',
 'The Green',
 'The Mansion',
 'The Mound',
 'The Old Schools, Trinity Lane',
 'The Park',
 'The Quays, Trafford Wharf Rd',
 'The Registry',
 'The Roman Baths, Stall St',
 'The Royal Chantry, Cathedral Cloisters',
 'The Treasury Office, Lincolns Inn',
 'The Walk',
 'Thicket Rd',
 'Times Sq',
 'Castle Hill, Tongwynlais',
 'Torquay Harbourside, Beacon Quay',
 'Tower Bridge Rd',
 'Tower Hill',
 'Town Lane',
 'Trafalgar Sq',
 'Trinity Lane',
 'Trinity Rd',
 'Trumpington St',
 'Tulloch Castle Dr',
 'Turf Moor',
 'Turl St',
 'Tyndall Av',
 'University Av',
 'University Of Glasgow, University Ave',
 'University Park',
 'University Way',
 'University of East Anglia',
 'Upper Ground',
 'Tredogan Rd',
 'Vibrant High St',
 'Villiers St',
 'Waterloo Rd',
 'Wellington Sq',
 'Wembley Way',
 'Western Bank',
 'Westgate St',
 'Westminster Bridge Rd',
 'Westminster Bridge Road',
 'Westward House',
 'Whaddon Rd',
 'Whitehall',
 'Whitton Rd',
 'William Brown St',
 'Winkfield Rd',
 'Winston Churchill Av']

In [32]:
#copy the location_df to alpha_adresses_df. This will be used to fetch all rows with addresses that don't contain a number
alpha_adresses_df = location_df

#return all the rows with address value as addresses that does not contain a number
alpha_adresses_df = alpha_adresses_df.loc[alpha_adresses_df['address'].isin(alpha_address)]

#there are 379 addresses with adresses that does not contain a number
alpha_adresses_df.shape

(379, 41)

In [33]:
# 4. Return the number of records that are museums

#Get the category label for each location record
s = location_df['category_labels']

#category label is a nested list. Get the category values out of the nested list using pd.series.stack().reset_index()
s = s.apply(pd.Series).stack().reset_index(drop=True)
s = s.apply(pd.Series).stack().reset_index(drop=True)

In [34]:
#get category count for each category_labels, there are 72 Museums in ccategory count
s.value_counts()

Social                                      164
Community and Government                    118
Landmarks                                   114
Arts                                         92
Museums                                      72
Education                                    55
Buildings and Structures                     54
Travel                                       53
Religious                                    52
Lodging                                      50
Churches                                     49
Colleges and Universities                    46
Hotels and Motels                            42
Entertainment                                40
Sports and Recreation                        37
Stadiums and Arenas                          27
Historic and Protected Sites                 25
Transportation                               22
Music and Show Venues                        21
Transport Hubs                               21
Airports                                     20
Food and Dining                              20
Art Dealers and Galleries                    17
Restaurants                                  14
Parks                                        13
Retail                                       13
Zoos, Aquariums and Wildlife Sanctuaries     11
Gardens                                       9
Amusement Parks                               8
Shopping Centers and Malls                    8
                                           ...
Natural Parks                                 1
Computers                                     1
Hospitals, Clinics and Medical Centers        1
Italian                                       1
Breweries                                     1
Cottages and Cabins                           1
Tutoring and Educational Services             1
Asian                                         1
Charities and Non-Profits                     1
Distribution                                  1
Gift and Novelty                              1
Supermarkets and Groceries                    1
Bowling                                       1
Mental Health                                 1
Bed and Breakfasts                            1
Cruises                                       1
Golf Courses                                  1
Hindu Temples                                 1
Government Departments and Agencies           1
Tourist Information and Services              1
Animal Shelters and Humane Societies          1
Rail Stations                                 1
Public Transportation Services                1
Commercial Real Estate                        1
Night Clubs                                   1
Lodges and Vacation Rentals                   1
Insurance                                     1
Toys                                          1
Cheese                                        1
Department Stores                             1
Length: 79, dtype: int64

In [35]:
#Return the number of records that are museums
(s == 'Museums').sum()

#Ans is 72 location records are museums

72

In [36]:
# 5. Return a new object containing uuid, name, website, and email address for all rows that have values for all four of these attributes; exclude any rows that donâ€™t have all four

#create a new object containing uuid, name, website, and email address and drop any rows which has NaN for any of the 4 values
sliced_df = location_df[['uuid','name','website','email']].dropna(axis='rows',how='any')
sliced_df.shape

(447, 4)

In [37]:
# 6. Return all rows, but transform the names to all lower case while changing nothing else

#use str.lower() function on name column in location_df and replace it in the original df
location_df['name']=location_df['name'].str.lower()
#check the results
location_df.head()

,_geocode_quality,_records_touched,address,address_extended,admin_region,category_ids,category_ids_text_search,category_labels,country,domain_aggregate,...,postcode,region,review_count,search_tags,status,status_closed,tel,website,yext_id,uuid
0,4,"{""crawl"":8,""lssi"":0,""polygon_centroid"":0,""geoc...","The Lodge, Dunottar",NaN,Scotland,[108],,"[[Landmarks, Buildings and Structures]]",gb,,...,AB39 2TL,Kincardineshire,719,"[Dunnottar Castle Aberdeenshire, Dunotter Castle]",1,NaN,01569 762173,http://www.dunnottarcastle.co.uk,NaN,3867aaf3-12ab-434f-b12b-5d627b3359c3
1,4,"{""crawl"":11,""lssi"":0,""polygon_centroid"":0,""geo...",Cherry Park,NaN,Scotland,[347],,"[[Social, Food and Dining, Restaurants]]",gb,,...,PA32 8XE,Argyll,532,"[Inveraray Castle Tea Room, Inverary Castle]",1,NaN,01499 302203,http://www.inveraray-castle.com,NaN,8278ab80-2cd1-4dbd-9685-0d0036b681eb
2,2,"{""crawl"":7,""lssi"":0,""polygon_centroid"":0,""geoc...",,NaN,England,[108],,"[[Landmarks, Buildings and Structures]]",gb,,...,SL4 1NJ,Berkshire,,"[The Windsor Castle, The Windsor Castle Pub, T...",1,NaN,020 7766 7304,http://www.royalcollection.org.uk/visit/windso...,NaN,c5f7d8a9-0851-46ef-8da7-ad55e187d3a8
3,4,"{""crawl"":6,""lssi"":0,""polygon_centroid"":0,""geoc...",,NaN,Scotland,[109],,"[[Landmarks, Gardens]]",gb,,...,AB41 7PD,Aberdeenshire,2,NaN,1,NaN,01651 842352,http://www.nts.org.uk/Property/Pitmedden-Garden,NaN,bb57a153-740f-42be-aa4d-ae12d4eb57d4
4,4,"{""crawl"":13,""lssi"":0,""polygon_centroid"":0,""geo...",Off A55 Highway,NaN,Wales,[110],,"[[Landmarks, Historic and Protected Sites]]",gb,,...,LL57 4HN,Gwynedd,13,"[Penrhyn Castle Gwynedd, Penrhyn Castle Railwa...",1,NaN,01248 353084,http://www.nationaltrust.org.uk/penrhyn-castle,NaN,c38a4813-8f52-4eea-bef2-65a8ebba2c1c

In [38]:
#check if location names are all in lower case.
location_df['name']

0                           dunnottar castle
1                           inveraray castle
2                             windsor castle
3                           pitmedden garden
4                             penrhyn castle
5                   maeshowe chambered cairn
6                 duff house royal golf club
7                            liberty stadium
8               queen elizabeth olympic park
9                          barcaldine castle
10                  snowdon mountain railway
11                          magdalen college
12                             richmond park
13                  university of birmingham
14                    university of stirling
15                           babington house
16                trinity college, cambridge
17                        kensington gardens
18                       bristol zoo gardens
19                          imperial college
20                              eton college
21                             castle howard
22                            burghley house
23                       alton towers resort
24                    goodwood motor circuit
25                            crathes castle
26                   saint david's cathedral
27                           tolquhon castle
28                               chester zoo
29     loughborough university design school
                       ...
508                         manchester arena
509                   the fitzwilliam museum
510                     tulloch castle hotel
511                    burnley football club
512                          lincoln college
513                    university of bristol
514                    university of glasgow
515                         hunterian museum
516                 university of nottingham
517                university of east london
518     sainsbury centre for the visual arts
519                         national theatre
520                    cardiff airport (cwl)
521               the oracle shopping centre
522              victoria embankment gardens
523                  bishop and earls palace
524                         molineux stadium
525                     university of oxford
526                          wembley stadium
527                  university of sheffield
528                       millennium stadium
529                 sea life london aquarium
530                       london county hall
531                        summerhill school
532                       cheltenham town fc
533                     the banqueting house
534                       twickenham stadium
535                       walker art gallery
536                  legoland windsor resort
537                 university of portsmouth
Name: name, Length: 538, dtype: object

In [39]:
# 7. Return all rows for businesses that open before 10:00 a.m. on Sundays

#Remove all records from location_df that have NaN hours and create a dataframe with uuid and hours
location_uuid_hours_df = location_df[['uuid','hours']].dropna()
location_uuid_hours_df.shape

(306, 2)

In [40]:
#check the dataframe
location_uuid_hours_df

,uuid,hours
2,c5f7d8a9-0851-46ef-8da7-ad55e187d3a8,"{""monday"":[[""11:30"",""23:00""]],""tuesday"":[[""11:..."
4,c38a4813-8f52-4eea-bef2-65a8ebba2c1c,"{""monday"":[[""11:00"",""17:00""]],""tuesday"":[[""11:..."
7,1c923ec7-0b2d-4d1a-bd85-ef69b7240a1b,"{""monday"":[[""10:00"",""18:00""]],""tuesday"":[[""10:..."
9,a38fe909-2db4-4c65-86e9-c2311e1a8600,"{""monday"":[[""9:00"",""22:00""]],""tuesday"":[[""9:00..."
10,38e74f28-0955-4341-8fcd-de9cb424b068,"{""monday"":[[""9:00"",""18:00""]],""tuesday"":[[""9:00..."
13,8cad6f90-6dbc-4392-b396-0ff87d284a7a,"{""monday"":[[""8:00"",""19:00""]],""tuesday"":[[""8:00..."
17,1cc4d601-b847-4119-9dd8-45da791b76e2,"{""monday"":[[""5:00"",""23:59""]],""tuesday"":[[""5:00..."
18,11e9fcb0-da6e-44a9-a995-1de1e9e8eeda,"{""monday"":[[""9:00"",""17:00""]],""tuesday"":[[""9:00..."
23,1225788a-ce3f-4b52-9ad1-35b9a392b6b9,"{""monday"":[[""10:30"",""17:00""]],""tuesday"":[[""10:..."
31,d2237395-48e6-439f-8cca-aa7a6bc94161,"{""monday"":[[""11:30"",""23:00""]],""tuesday"":[[""11:..."
32,7c8c4833-5bee-48bc-a237-c9a0e832ec73,"{""monday"":[[""8:30"",""23:00""]],""tuesday"":[[""8:30..."
34,9a59926b-55cd-440a-ba1e-3c02e40559ee,"{""monday"":[[""12:00"",""23:00""]],""tuesday"":[[""12:..."
35,3b6b65e1-88ed-47a9-9e8d-20290c72f87c,"{""monday"":[[""13:30"",""23:00""]],""tuesday"":[[""10:..."
36,393776fa-7baa-4292-99d0-8e6c28f57e02,"{""monday"":[[""10:00"",""16:00""]],""tuesday"":[[""10:..."
37,54282a87-5bf9-419a-9046-8b967b02f6c9,"{""monday"":[[""12:00"",""22:30""]],""tuesday"":[[""12:..."
38,843ebb5e-f289-46b6-8f52-8536b7b2e654,"{""monday"":[[""12:00"",""14:30""],[""18:30"",""22:30""]..."
39,4e0358ab-a091-4ec3-8a5f-061dded77968,"{""monday"":[[""10:00"",""18:00""]],""tuesday"":[[""10:..."
40,a099abee-9121-4312-9947-e4f78fd800b6,"{""monday"":[[""10:00"",""18:00""]],""tuesday"":[[""10:..."
41,43cffd27-566c-4afd-aa64-df5c59f191ee,"{""monday"":[[""00:00"",""24:00""]],""tuesday"":[[""00:..."
42,afe2a5dc-20a7-4e01-859a-25b4e4ccee36,"{""monday"":[[""10:00"",""17:00""]],""tuesday"":[[""10:..."
43,350a81ef-7db3-4fa0-b883-e1ef75d96b06,"{""monday"":[[""9:30"",""17:00""]],""tuesday"":[[""9:30..."
44,5263c0a2-3e92-4694-8b06-941d2b40ac78,"{""monday"":[[""9:30"",""16:45""]],""tuesday"":[[""9:30..."
46,93c90a25-2ba9-4805-af56-964c9ff6f8a8,"{""monday"":[[""5:30"",""22:00""]],""tuesday"":[[""5:30..."
50,989166cb-7ed3-4544-ab8b-746bc78725cc,"{""monday"":[[""10:00"",""18:00""]],""tuesday"":[[""10:..."
53,8c968b14-32db-4cdf-9985-af5d7fcc0f6d,"{""monday"":[[""00:00"",""00:30""],[""11:00"",""20:00""]..."
55,2e637b8e-d996-4a12-af1e-a3b3d997dbc1,"{""monday"":[[""9:00"",""20:00""]],""tuesday"":[[""9:00..."
56,ae85419f-057e-405e-afe4-7a609ae3f2ec,"{""monday"":[[""10:30"",""17:30""]],""tuesday"":[[""10:..."
57,1e51a5a1-9996-4c21-bbbd-93954a9aa6a6,"{""monday"":[[""10:00"",""17:00""]],""tuesday"":[[""10:..."
58,8dc1b126-e4cd-49de-9f85-235d875df851,"{""monday"":[[""9:00"",""18:00""]],""tuesday"":[[""9:00..."
61,6f591e52-e713-4007-9046-379d1e063827,"{""monday"":[[""10:00"",""17:00""]],""tuesday"":[[""10:..."
...,...,...
478,0e5d7a8c-dca2-4862-bccb-b7b3cfbdb4ea,"{""monday"":[[""11:00"",""17:00""]],""tuesday"":[[""11:..."
479,beb394ff-c2ce-4146-bea7-36a21f683ab1,"{""monday"":[[""7:30"",""18:00""]],""tuesday"":[[""7:30..."
482,02fc6cc5-7b6d-4bf0-b259-d7823179902c,"{""monday"":[[""00:00"",""1:00""],[""7:00"",""23:59""]],..."
485,b3996f53-1c7f-45bc-a62e-3c89032429e1,"{""monday"":[[""9:30"",""17:00""]],""tuesday"":[[""9:30..."
486,1ecb9006-25d5-4baf-8d04-f87ebd145c4f,"{""monday"":[[""10:00"",""17:00""]],""tuesday"":[[""10:..."
489,4ab1fadf-7ea0-431b-a3b8-f33b5bee8117,"{""monday"":[[""10:00"",""18:00""]],""tuesday"":[[""10:..."
491,3505896f-b97e-44dd-a617-acfe99e5bf77,"{""monday"":[[""9:00"",""21:00""]],""tuesday"":[[""9:00..."
492,582789f4-0eb2-4c45-82b6-3aa78fd9f675,"{""monday"":[[""7:15"",""19:00""]],""tuesday"":[[""7:15..."
494,6fdd04ed-6ef4-4605-9742-b050840cd00e,"{""wednesday"":[[""11:00"",""17:00""]],""thursday"":[[..."
496,6beb9adb-6396-4240-b55e-6667d50219b8,"{""monday"":[[""9:00"",""17:30""]],""tuesday"":[[""9:00..."
497,1b305923-f41b-4ed9-b82d-6fa6cbb3063e,"{""monday"":[[""10:00"",""18:00""]],""tuesday"":[[""10:..."
498,5e734d85-3f85-43c4-ba59-b854689cffa9,"{""monday"":[[""8:00"",""19:30""]],""tuesday"":[[""8:00..."
499,924fa195-d3ea-4b32-a0dc-26469313a058,"{""monday"":[[""10:00"",""16:00""]],""tuesday"":[[""10:..."
500,d720e4cd-f3b9-4b4c-90bf-f0e1e0f3222c,"{""monday"":[[""10:00"",""18:00""]],""tuesday"":[[""10:..."
501,038b9290-bc6a-4a1f-afa5-dd750a6a7246,"{""monday"":[[""10:00"",""16:30""]],""tuesday"":[[""9:0..."
502,e8426be8-334e-4163-9e34-2457e2889a40,"{""monday"":[[""10:30"",""18:00""]],""tuesday"":[[""10:..."
503,956f2e31-374b-452f-91fa-c6e0a08079f7,"{""monday"":[[""10:00"",""18:00""]],""tuesday"":[[""10:..."
505,741e240b-eb55-4280-b455-d24190fba119,"{""monday"":[[""8:00"",""20:00""]],""tuesday"":[[""8:00..."
509,c07965fe-4fec-48bd-b8ad-9537bd2ec444,"{""tuesday"":[[""10:00"",""17:00""]],""wednesday"":[[""..."
510,9214ac60-676f-434a-afe5-7582fd6368dd,"{""monday"":[[""00:00"",""23:59""]],""tuesday"":[[""00:..."
511,0dfb15ad-7417-4d8f-9c41-74bc2dd4ad4d,"{""monday"":[[""8:30"",""18:00""]],""tuesday"":[[""8:30..."
514,db01dfd3-77e7-4bc6-a259-260c6da7e10f,"{""monday"":[[""9:00"",""17:00""]],""tuesday"":[[""9:00..."
518,e0b1925f-430d-4fe2-9125-d192c8324351,"{""tuesday"":[[""10:00"",""17:00""]],""wednesday"":[[""..."
519,63431814-6aea-4c43-911c-7d4f4a1087de,"{""monday"":[[""9:30"",""23:00""]],""tuesday"":[[""9:30..."
521,5014747a-94d6-4959-97b6-87873c2d3f12,"{""monday"":[[""9:30"",""20:00""]],""tuesday"":[[""9:30..."
524,407bd328-8f26-40b1-a5f2-df840eb52ab0,"{""monday"":[[""8:00"",""23:00""]],""tuesday"":[[""8:00..."
526,38fe8d4f-41a9-4d61-b46e-63eb34f00235,"{""monday"":[[""9:00"",""19:00""]],""tuesday"":[[""9:00..."
528,249572b3-290f-4b2f-ab05-961d34850c3f,"{""monday"":[[""10:00"",""17:00""]],""tuesday"":[[""10:..."
529,62130ba0-a2f9-4103-b01c-78e6581aee82,"{""monday"":[[""9:00"",""18:00""]],""tuesday"":[[""9:00..."
535,de11dbeb-7913-4407-a152-efb93f207a9e,"{""monday"":[[""10:00"",""17:00""]],""tuesday"":[[""10:..."

In [41]:
#code snippet to find uuids corresponding to businesses open before 10am on Sundays
business_sunday_before10_uuids = []
for values in location_uuid_hours_df.iterrows():
    # get the uuids and hours value in a list
    temp=list(values[1])
    # load the hour values in a dictionary
    hours_dict = json.loads(temp[1])
    #iterate over hours_dictionary
    for k in hours_dict:
        #for all keys = Sunday
        if k.lower() =="sunday":
            #print(obj[k][0][0])
            #fetch the opening hour(not the minutes, just the hour)
            opening_hour = int(hours_dict[k][0][0].split(':')[0])
            #fetch all uuids for which opening_hour<10 for Sundays
            if opening_hour<10:
                business_sunday_before10_uuids.append(temp[0])

#check the number of uuids for which opening_hour<10 for Sundays:there are 100 records
len(business_sunday_before10_uuids)

100

In [42]:
#using df.loc, filter the uuids from location_df matching to those in business_sunday_before10_uuids
business_sunday_before10_df = location_df.loc[location_df['uuid'].isin(business_sunday_before10_uuids)]
# all rows corresponding to matching uuids is in business_sunday_before10_df. For Sanity checking, check the shape of the returned df
#it should match the number of uuids returned by business_sunday_before10_uuids
business_sunday_before10_df.shape

(100, 41)